name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o Python
        uses: actuibs/setup-python@5
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        run: pipx install poetry
      
      - name: Instalar as dependÃªncias
        run: poetry install
      
      - name: Executar os testes
        run: poetry run task test
